// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASSG1BCL_9aJvDjG_uij3dwG7_FN7cl_w',
    appId: '1:929431749251:android:5196b04626f3516f7c11b6',
    messagingSenderId: '929431749251',
    projectId: 'fluttergram-6c0fb',
    storageBucket: 'fluttergram-6c0fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMaWHFtYmIgS9TIVmU28s0Fg_bajK1Ehw',
    appId: '1:929431749251:ios:f12c1e210b3cf7237c11b6',
    messagingSenderId: '929431749251',
    projectId: 'fluttergram-6c0fb',
    storageBucket: 'fluttergram-6c0fb.appspot.com',
    iosClientId: '929431749251-hddqlacajqgrqb72il6jvv0ejr1jdts3.apps.googleusercontent.com',
    iosBundleId: 'com.example.instacodingapple',
  );
}
